package com.bsuc.homestay.entiy;

import java.util.Date;

public class AdminPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ADMIN_ID
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ADMIN_USERNAME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private String adminUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ADMIN_PASSWORD
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private String adminPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ADMIN_NAME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ADMIN_PHONE
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private String adminPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.IS_DELETE
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.REVISION
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private Integer revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.CREATED_BY
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.CREATED_TIME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.UPDATED_BY
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.UPDATED_TIME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ADMIN_ID
     *
     * @return the value of admin.ADMIN_ID
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ADMIN_ID
     *
     * @param adminId the value for admin.ADMIN_ID
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ADMIN_USERNAME
     *
     * @return the value of admin.ADMIN_USERNAME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public String getAdminUsername() {
        return adminUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ADMIN_USERNAME
     *
     * @param adminUsername the value for admin.ADMIN_USERNAME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setAdminUsername(String adminUsername) {
        this.adminUsername = adminUsername == null ? null : adminUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ADMIN_PASSWORD
     *
     * @return the value of admin.ADMIN_PASSWORD
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ADMIN_PASSWORD
     *
     * @param adminPassword the value for admin.ADMIN_PASSWORD
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ADMIN_NAME
     *
     * @return the value of admin.ADMIN_NAME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ADMIN_NAME
     *
     * @param adminName the value for admin.ADMIN_NAME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ADMIN_PHONE
     *
     * @return the value of admin.ADMIN_PHONE
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ADMIN_PHONE
     *
     * @param adminPhone the value for admin.ADMIN_PHONE
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.IS_DELETE
     *
     * @return the value of admin.IS_DELETE
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.IS_DELETE
     *
     * @param isDelete the value for admin.IS_DELETE
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.REVISION
     *
     * @return the value of admin.REVISION
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public Integer getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.REVISION
     *
     * @param revision the value for admin.REVISION
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setRevision(Integer revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.CREATED_BY
     *
     * @return the value of admin.CREATED_BY
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.CREATED_BY
     *
     * @param createdBy the value for admin.CREATED_BY
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.CREATED_TIME
     *
     * @return the value of admin.CREATED_TIME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.CREATED_TIME
     *
     * @param createdTime the value for admin.CREATED_TIME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.UPDATED_BY
     *
     * @return the value of admin.UPDATED_BY
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.UPDATED_BY
     *
     * @param updatedBy the value for admin.UPDATED_BY
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.UPDATED_TIME
     *
     * @return the value of admin.UPDATED_TIME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.UPDATED_TIME
     *
     * @param updatedTime the value for admin.UPDATED_TIME
     *
     * @mbggenerated Sun Apr 12 04:13:09 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}